apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: mygo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mygo
  template:
    metadata:
      labels:
        app: mygo
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'vault-role'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/agent-inject-secret-envvault: 'secret/data/mygo/config'
        vault.hashicorp.com/agent-inject-template-envvault: |
          {{ with secret "secret/data/mygo/config" }}
            {{ range $k, $v := .Data.data }}
              export {{ $k }}={{ $v }}
            {{ end }}
          {{ end }}
    spec:
      serviceAccountName: vault-role
      containers:
      - name: mygo
        image: rizqifauzy10/mygo-app:latest
        env:
        - name: ENV
          value: /vault/secrets/envvault
        ports:
        - containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: mygo
spec:
  selector:
    app: mygo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080